@startuml zinbei

zinbei <--> zinbeiw
zinbei <--> zinbeie

zinbei : オプション(各種機能)
zinbei : ロゴ表示

zinbeiw : 対話的プログラム(多彩な機能)
zinbeiw : 対話的プログラム(Tab入力補完機能)

zinbeie : zinbeijett、engine(1.2.1)のクローン

@enduml
