# -------------------------------------
require 'minitest'
require 'minitest/autorun'
require 'minitest/unit'
require 'minitest/benchmark'
require 'minitest/runner'
require 'tanraku'
require 'simplecov'
# -------------------------------------
